from flask import Flask, render_template, jsonify
import random

app = Flask(__name__)

word_pairs = [
    ("abbreviate", "לקצר"),
    ("abdomen", "בטן"),
    ("ability", "יכולת"),
    ("abnormal", "לא נורמלי"),
    ("abolish", "לבטל"),
    ("above", "מעל"),
    ("absolute", "מוחלט, מושלם"),
    ("absolutely", "באופן מוחלט"),
    ("absorb", "לקלוט, לספוג, להתעמק"),
    ("absorbent", "בעל כושר ספיגה"),
    ("acceptable", "מקובל"),
    ("account", "חשבון"),
    ("[to] admit into", "להכניס"),
    ("admittance", "הכנסה"),
    ("ambiguity", "דו משמעות"),
    ("[to] appeal", "לבקש"),
    ("approval", "אישור"),
    ("argument", "טענה"),
    ("[to] arouse", "לעורר"),
    ("assertively", "בביטחון"),
    ("blindness", "עיוורון"),
    ("[to] bother", "להפריע"),
    ("[to] brake", "לעצור"),
    ("bright", "בהיר"),
    ("[to] brighten", "להבהיר"),
    ("brightness", "בהירות"),
    ("[to] broaden", "להרחיב"),
    ("candidly", "בכנות"),
    ("consideration", "עיון"),
    ("consolation", "נחמה"),
    ("contradiction", "ניגוד"),
    ("contribution", "תרומה"),
    ("conversion", "החלפה"),
    ("[to] critique", "לבקר"),
    ("crossroads", "צומת"),
    ("dedicated", "הקדיש"),
    ("dedication", "הקדשה"),
    ("deduction", "מסקנה"),
    ("deeply", "באופן מעמיק"),
    ("definitely", "בהחלט"),
    ("deliberation", "דיון"),
    ("deliberative", "דיוני"),
    ("detection", "גילוי"),
    ("distraction", "הסחת דעת"),
    ("[to] disturb", "להפריע"),
    ("efficiency", "יעילות"),
    ("[to] enlighten", "להסביר"),
    ("[to] ensure", "להבטיח"),
    ("[to] evolve", "לפתח"),
    ("examination", "בחינה"),
    ("expansion", "התרחבות"),
    ("expectancy", "ציפייה"),
    ("expensive", "יקר"),
    ("factor", "גורם"),
    ("far", "רחוק"),
    ("farther", "יותר רחוק"),
    ("fear", "פחד"),
    ("formation", "מבנה"),
    ("foundation", "יסוד"),
    ("[to] generate", "לייצר"),
    ("genesis", "בראשית"),
    ("growth", "גדילה"),
    ("[to] harm", "לפגוע"),
    ("height", "גובה"),
    ("[to] horrify", "להפחיד"),
    ("insistence", "התעקשות"),
    ("[to] inspect", "לבדוק"),
    ("interpretation", "פרשנות"),
    ("intriguing", "מעניין"),
    ("invention", "המצאה"),
    ("joint", "חיבור"),
    ("journey", "טיול"),
    ("low", "נמוך"),
    ("maturity", "בגרות"),
    ("mixture", "תערובת"),
    ("modification", "השתנות"),
    ("obedience", "צייתנות"),
    ("preventive", "מונע"),
    ("purity", "טוהר"),
    ("recommendation", "המלצה"),
    ("recovery", "החלמה"),
    ("regional", "אזורי"),
    ("relief", "רווחה"),
    ("[to] remind", "להזכיר"),
    ("repetition", "חזרה"),
    ("replacement", "חלופה"),
    ("representative", "ייצוגי"),
    ("reproduction", "שחזור"),
    ("requirement", "דרישה"),
    ("rhythm", "קצב"),
    ("scare", "פחד"),
    ("sensitivity", "רגישות"),
    ("shrewd", "חכם"),
    ("[to] stink", "להסריח"),
    ("supposition", "הנחה"),
    ("task", "מטלה"),
    ("tolerance", "סיבולת"),
    ("training", "אימון"),
    ("[to] valuate", "לאמוד"),
    ("verdict", "פסק דין"),
    ("verifiable", "בר אימות"),
    ("[to] vote", "להצביע"),
    ("wealth", "עושר"),
    ("within", "בפנים"),
    ("zip", "זמזום"),
    ("accessible", "נגיש"),
    ("accidental", "מקרי"),
    ("accompaniment", "ליווי"),
    ("adherence", "היצמדות"),
    ("agglomeration", "ערימה"),
    ("aim", "תכלית"),
    ("allowable", "חוקי"),
    ("[to] anguish", "לסבול"),
    ("[to] annex", "לצרף"),
    ("[to] ascertain", "לוודא"),
    ("assertion", "טענה"),
    ("audacious", "נועז"),
    ("audience", "קהל"),
    ("authoritative", "מהימן"),
    ("avaricious", "חמדן"),
    ("[to] awe", "לעורר יראת כבוד"),
    ("axis", "ציר"),
    ("bait", "פיתיון"),
    ("belief", "אמונה"),
    ("[to] bestow", "להעניק"),
    ("[to] bridle", "לרסן"),
    ("brutish", "בהמי"),
    ("candid", "כן"),
    ("[to] certify", "לאשר"),
    ("characteristic", "מובהק"),
    ("complaisance", "נכונות לרצות אחרים"),
    ("composition", "חיבור"),
    ("compulsory", "של חובה"),
    ("confidential", "חסוי"),
    ("[to] conquer", "לכבוש"),
    ("conquest", "כיבוש"),
    ("constitution", "חוקה"),
    ("deducible", "ניתן להסקה"),
    ("derivation", "גזירה"),
    ("destiny", "גורל"),
    ("devotion", "התמסרות"),
    ("dictation", "תכתיב"),
    ("discrepancy", "שוני"),
    ("dispensable", "שאפשר לוותר עליו"),
    ("distortion", "סילוף"),
    ("distribution", "תפוצה"),
    ("diversion", "הטיה"),
    ("domestic", "ביתי"),
    ("durable", "יציב"),
    ("emergent", "מגיח"),
    ("employment", "עיסוק"),
    ("enlightened", "נאור"),
    ("eruption", "התפרצות"),
    ("essential", "מהותי"),
    ("[to] estimate", "להעריך"),
    ("eulogy", "הספד"),
    ("[to] evacuate", "לפנות"),
    ("evacuation", "פינוי"),
    ("eventual", "סופי"),
    ("evidence", "ראיה"),
    ("[to] explore", "לחקור"),
    ("extensive", "מקיף"),
    ("factory", "מפעל"),
    ("fascination", "משיכה"),
    ("fiction", "סיפורת"),
    ("figure", "דמות"),
    ("fleet", "מהיר"),
    ("foreseeable", "צפוי מראש"),
    ("[to] fracture", "להישבר"),
    ("fringe", "גדיל"),
    ("generous", "נדיב"),
    ("germ", "ראשית"),
    ("[to] glare", "להביט בזעם"),
    ("identity", "זהות"),
    ("[to] imply", "לרמוז"),
    ("inanimate", "דומם"),
    ("incidental", "מקרי"),
    ("inclusion", "שיתוף"),
    ("incredible", "מדהים"),
    ("[to] industrialize", "לתעש"),
    ("influence", "השפעה"),
    ("[to] intrigue", "לסקרן"),
    ("intrigued", "מסוקרן"),
    ("[to] invade", "לפלוש"),
    ("invasion", "פלישה"),
    ("[to] invite", "להזמין"),
    ("jail", "כלא"),
    ("kernel", "עיקר"),
    ("languid", "נרפה"),
    ("[to] languish", "להיחלש"),
    ("languor", "כבדות"),
    ("[to] legislate", "לחוקק"),
    ("livelihood", "מחיה"),
    ("masterpiece", "יצירת מופת"),
    ("[to] memorize", "לשנן"),
    ("modest", "צנוע"),
    ("municipality", "עירייה"),
    ("neat", "נקי"),
    ("objective", "תכלית"),
]

def build_quiz_data():
    selected_pairs = random.sample(word_pairs, 30)
    quiz_data = []
    for eng, heb in selected_pairs:
        wrongs = [h for e, h in word_pairs if h != heb]
        options = random.sample(wrongs, 3) + [heb]
        random.shuffle(options)
        quiz_data.append({
            "question": f"What is the meaning of '{eng}'?",
            "answers": options,
            "correct": options.index(heb)
        })
    random.shuffle(quiz_data)
    return quiz_data



@app.route("/")
def index():
    return render_template("index.html")

@app.route("/questions")
def get_questions():
    return jsonify(build_quiz_data())

if __name__ == "__main__":
    port = int(os.environ.get("PORT", 5000))
    app.run(host="0.0.0.0", port=port)